# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4e16f652224536b29a3aee2f7b63dc23c5c9d6c3b901ee213270bb160c8ca1367703c8de8e808e6fbbb799b2d1464aa6bd001dcd9a0eb46a7df5d47a65775e1

test:
  secret_key_base: 55db70f5cb6ee96182c683d85175f20ab3f5275f62151757d8f915fb71ee8dfee1714a20fb879d0c3e899b6ca33726668419d8a859ed53e44f8a33df5c0c4591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
